### ISSUE TITLE
Runner do not start

### ISSUE THREAD

**Issue by doinasava1** [fbascheper/SoapUI-MockService-Docker-image#3]
Hi, I am trying to use this image to start a SOAPUI Mock service in a docker container. I copied my project xml file in soapui-prj folder and I created the image. When i try to run the service in the docker container I don't get any errors but still i "docker ps" does not show any container running.
My online command is: 
docker run -P -it --rm -e MOCK_SERVICE_NAME=FindPatientMockService -e MOCK_SERVICE_PATH=/FindPatientMockService -e PROJECT=/home/soapui/soapui-prj/FindPatientMockService-soapui-project.xml eaba31b9874b
eaba31b9874b - is my image id
The output is:
Starting Mock-service=FindPatientMockService using url-path=/FindPatientMockService from SoapUI-project=/home/soapui/soapui-prj/FindPatientMockService-soapui-project.xml

 SOAPUI_HOME = /home/soapui/SoapUI-5.2.1

SoapUI 5.2.1 MockService Runner
20:06:10,676 INFO  [DefaultSoapUICore] Creating new settings at [/home/soapui/soapui-settings.xml]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
20:06:11,557 INFO  [PluginManager] 0 plugins loaded in 2 ms
20:06:11,557 INFO  [DefaultSoapUICore] All plugins loaded
20:06:12,270 INFO  [WsdlProject] Loaded project from [file:/home/soapui/soapui-prj/FindPatientMockService-soapui-project.xml]
20:06:12,280 INFO  [SoapUIMockServiceRunner] Running MockService [FindPatientMockService] in project [FindPatientMockService]
20:06:12,280 INFO  [SoapUIMockServiceRunner] Press any key to terminate
20:06:12,281 INFO  [SoapUIMockServiceRunner] Started 0 runners
Press any key to terminate...

In few seconds the prompt is displayed and "docker ps -a" does not show any running containers

**Comment by doinasava1** [comment]
Issue resolved, I've found that the MOCK_SERVICE_NAME passed did not correspond with the name of the service in SoapUI. Thank you

**Comment by fbascheper** [comment]
Thanks for following up on this issue, and yes that's necessary.
