### ISSUE TITLE
how to add configurations jars in ${SOAPUI}/bin/ext directory when using this image

### ISSUE THREAD

**Issue by piyushjhamb** [fbascheper/SoapUI-MockService-Docker-image#4]
how to add configurations jars in ${SOAPUI}/bin/ext directory when using this image

**Comment by vishnumishra88** [comment]
Looking for solution to this for lukastosic/docker-soapui image.

**Comment by fbascheper** [comment]
You can use this image as a base image from your own Dockerfile.
