### ISSUE TITLE
Problem with shell script

### ISSUE THREAD

**Issue by EriKra** [fbascheper/SoapUI-MockService-Docker-image#6]
Hi fbascheper, 

thank you for your interesting Project.

My Problem - building of Dockerimage ends with the following Message:
```
The command '/bin/sh -c yum -y install wget &&     wget --no-check-certificate -
-no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://d
ownload.oracle.com/otn-pub/java/jdk/8u92-b14/jdk-8u92-linux-x64.rpm &&     echo
"881ee6070efcb427204f04c98db9a173  jdk-8u92-linux-x64.rpm" >> MD5SUM &&     md5s
um -c MD5SUM &&     rpm -Uvh jdk-8u92-linux-x64.rpm &&     yum -y remove wget &&
     rm -f jdk-8u92-linux-x64.rpm MD5SUM' returned a non-zero code: 8
```

What can i do? Sorry, Im a Linux noob an docker newbee :/ Here is the screenshot with all information of the build-process.
![docker-build](https://cloud.githubusercontent.com/assets/12786542/26676135/d21839fe-46c6-11e7-8423-3ff486996b59.PNG)

The container is running, if i start it with your run command.
I dont know that the problem above causes my problem to get no response by calling your soap mockservice with the following URLs. 
- localhost:8080/BLZMockService
- 192.168.99.100:8080/BLZMockService (docker VM IP ip)
If my URL-Path isnt correct, what should be the correct URL-Path to verify that the example mockservice is running? 

Another question for me is that in your example/default project.xml, the host of the mockservice is the name of a computer, should i change it to 127.0.0.1, because thats running in the container?

![host](https://cloud.githubusercontent.com/assets/12786542/26676483/47530acc-46c8-11e7-8021-1a7d6bf58979.PNG)

Thank you, and kind regards from Berlin!

Erik

**Comment by EriKra** [comment]
ok, the download of the jdk failed, i wil try to use a bit more this way:
https://github.com/Mashape/docker-java8/blob/master/Dockerfile

**Comment by fbascheper** [comment]
I've updated the JDK to JDK 8u181 and SoapUI to the latest versions. Today's build at [Docker Hub](https://hub.docker.com/r/fbascheper/soapui-mockservice-runner/builds/) succeeded. 

Closing this issue.
