### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Ruud-Wiegers** [fbascheper/SoapUI-MockService-Docker-image#7]
My team is interested in using this docker image to set up a mock service in our testing environment. 

However, I don't see a license file, which means the default applies: you retain the exclusive copyright, and we're not allowed to use the code.

Would you be open to publishing the code under a more permissive license?

**Comment by fbascheper** [comment]
Absolutely, yes. I'm out of the office today, but I'll add a licence file ASAP.
