### ISSUE TITLE
Ability to set port on which the runner runs

### ISSUE THREAD

**Issue by SudheendraSingh** [fbascheper/SoapUI-MockService-Docker-image#8]
The Mock runner seems to run on port 8080 by default. This is an issue when we want to run multiple SOAP UI projects. Is there any environmental variable similar to MOCK_SERVICE where we can set the port the soap ui mock service will run? 
In my SOAP UI project, I have mentioned a different port (8200), yet it runs it on 8080.

**Comment by fbascheper** [comment]
You should use the -p option for this.  

E.g. if I do the following (see the README.md):

````
docker pull fbascheper/soapui-mockservice-runner
mkdir -p $HOME/soapui-test-project
cd $HOME/soapui-test-project 
wget https://raw.githubusercontent.com/fbascheper/SoapUI-MockService-Docker-image/master/soapui-prj/default-soapui-project.xml

docker run -P -it --rm \
        -p 30080:8080 \
        -v "$HOME/soapui-test-project:/home/soapui/soapui-prj/" \
        -e MOCK_SERVICE_NAME="BLZ-SOAP11-MockService" \
        -e PROJECT=/home/soapui/soapui-prj/default-soapui-project.xml \
        --privileged \
         fbascheper/soapui-mockservice-runner:latest
````

And open localhost:30080 I see a sample wsdl.
